/* Generated By:JavaCC: Do not edit this line. CompilerConstants.java */
package grammaire.genere;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CompilerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EOL = 55;
  /** RegularExpression Id. */
  int CEOL = 57;
  /** RegularExpression Id. */
  int IMM = 59;
  /** RegularExpression Id. */
  int NUM = 60;
  /** RegularExpression Id. */
  int IND = 61;
  /** RegularExpression Id. */
  int PLUS = 62;
  /** RegularExpression Id. */
  int MOINS = 63;
  /** RegularExpression Id. */
  int VALUE = 64;
  /** RegularExpression Id. */
  int LETTER = 65;
  /** RegularExpression Id. */
  int DIGIT = 66;
  /** RegularExpression Id. */
  int DAT = 67;
  /** RegularExpression Id. */
  int MOV = 68;
  /** RegularExpression Id. */
  int ADD = 69;
  /** RegularExpression Id. */
  int SUB = 70;
  /** RegularExpression Id. */
  int MUL = 71;
  /** RegularExpression Id. */
  int DIV = 72;
  /** RegularExpression Id. */
  int MOD = 73;
  /** RegularExpression Id. */
  int JMP = 74;
  /** RegularExpression Id. */
  int JMZ = 75;
  /** RegularExpression Id. */
  int JMN = 76;
  /** RegularExpression Id. */
  int DJN = 77;
  /** RegularExpression Id. */
  int CMP = 78;
  /** RegularExpression Id. */
  int SLT = 79;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_SL_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\\"\"",
    "\"\\\\\"",
    "\"!\"",
    "\"%\"",
    "\"&\"",
    "\"\\\'\"",
    "\"*\"",
    "\".\"",
    "\"/\"",
    "\";\"",
    "\"<\"",
    "\">\"",
    "\"=\"",
    "\"?\"",
    "\"[\"",
    "\"]\"",
    "\"^\"",
    "\"`\"",
    "\"{\"",
    "\"}\"",
    "\"~\"",
    "\"|\"",
    "\"\\u0000\"",
    "\"\\u0001\"",
    "\"\\u0002\"",
    "\"\\u0003\"",
    "\"\\u0004\"",
    "\"\\u0005\"",
    "\"\\u0006\"",
    "\"\\u0007\"",
    "\"\\b\"",
    "\"\\u000b\"",
    "\"\\f\"",
    "\"\\u000e\"",
    "\"\\u000f\"",
    "\"\\u0010\"",
    "\"\\u0011\"",
    "\"\\u0012\"",
    "\"\\u0013\"",
    "\"\\u0014\"",
    "\"\\u0015\"",
    "\"\\u0016\"",
    "\"\\u0017\"",
    "\"\\u0018\"",
    "\"\\u0019\"",
    "\"\\u001a\"",
    "\"\\u001b\"",
    "\"\\u001c\"",
    "\"\\u001d\"",
    "\"\\u001e\"",
    "\"\\u001f\"",
    "\"\\u007f\"",
    "<EOL>",
    "\"//\"",
    "<CEOL>",
    "<token of kind 58>",
    "\"#\"",
    "\"$\"",
    "\"@\"",
    "\"+\"",
    "\"-\"",
    "<VALUE>",
    "<LETTER>",
    "<DIGIT>",
    "\"DAT\"",
    "\"MOV\"",
    "\"ADD\"",
    "\"SUB\"",
    "\"MUL\"",
    "\"DIV\"",
    "\"MOD\"",
    "\"JMP\"",
    "\"JMZ\"",
    "\"JMN\"",
    "\"DJN\"",
    "\"CMP\"",
    "\"SLT\"",
  };

}
